config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'

  get "/login"          => "sessions#new"
  post "/login"         => "sessions#create"
  delete "/logout"      => "sessions#destroy"
  get '/auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: 'sessions#new'

  resources :dashboard, only: [:index]
  resources :jobs do
    resources :contacts, except: [:index, :show]
    resources :checklists, except: [:index, :show]
  end
  resources :companies, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/checklist.rb
class Checklist < ApplicationRecord
  belongs_to :job

  validates :task, presence: true
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :job

  validates :name, presence: true

  validates :email, presence: { if: -> { phone.blank? } }
  validates :phone, presence: { if: -> { email.blank? } }
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :user
  belongs_to :status
  has_many :contacts, dependent: :destroy
  has_many :checklists, dependent: :destroy

  validates :company, :title, :city, :description, :state, :salary, presence: true

  def location
    "#{city}, #{state}"
  end
end

app/models/status.rb
class Status < ApplicationRecord
  has_many :jobs

  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord

  has_many :jobs

  validates :uid, :first_name, :last_name, :email, :token, :expires_at, :image_url, presence: true

  def self.from_omniauth(auth_info)
    where(uid: auth_info[:uid]).first_or_create do |new_user|
      new_user.uid         = auth_info["uid"]
      new_user.first_name  = auth_info["info"]["first_name"]
      new_user.last_name   = auth_info["info"]["last_name"]
      new_user.email       = auth_info["info"]["email"]
      new_user.token       = auth_info["credentials"]["token"]
      new_user.expires_at  = auth_info["credentials"]["expires_at"]
      new_user.image_url   = auth_info["info"]["image"]
    end
  end

  def name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :require_user

  helper_method :current_user,
                :require_user

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

  def require_user
    unless current_user
      flash[:notice] = "You Must Log in to View this Page"
      redirect_to login_path
    end
  end

end

app/controllers/checklists_controller.rb
class ChecklistsController < ApplicationController

  def new
    @checklist = Checklist.new
  end

  def create
    job = current_user.jobs.find(params[:job_id])
    job.checklists.create(checklist_params)
    redirect_to job_path(job)
  end

  def destroy
    job = current_user.jobs.find(params[:job_id])
    checklist = job.checklists.find(params[:id])
    checklist.delete
    redirect_to job_path(job)
  end

  private

  def checklist_params
    params.require(:checklist).permit(:task)
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

  def show
    @job = current_user.jobs.find(params[:id])
    remote_ip = request.remote_ip
    @company = CompanyService.new.execute(@job.company, remote_ip)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
    @contact = Contact.new
  end

  def create
    job = current_user.jobs.find(params[:job_id])
    contact = job.contacts.create(contact_params)
    if contact.save
      flash[:notice] = "Contact added!"
    end
    redirect_to job_path(job)
  end

  def edit
    job = Job.find(params[:job_id])
    @contact = job.contacts.find(params[:id])
  end

  def update
    job = current_user.jobs.find(params[:job_id])
    contact = job.contacts.find(params[:id])
    if contact.update(contact_params)
      flash[:notice] = "Contact successfully updated!"
    else
      flash[:notice] = "Unable to update contact. Try again."
    end
    redirect_to job_path(job)
  end

  def destroy
    job = current_user.jobs.find(params[:job_id])
    contact = job.contacts.find(params[:id])
    if contact.delete
      flash[:notice] = "#{contact.name} successfully deleted"
    else
      flash[:notice] = "There was a problem deleting this contact. Please try again"
    end
    redirect_to job_path(job)
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :phone, :email, :image_url)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @jobs = current_user.jobs.page(params[:page])
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  def show
    @job = Job.find(params[:id])
    @keywords = WatsonService.new.get_analysis(@job.description)
    @company = CompanyService.new.execute(@job.company, request.remote_ip)
  end

  def new
    @job = Job.new
    @statuses = Status.all
  end

  def create
    job = current_user.jobs.new(job_params)
    if job.save
      flash[:notice] = "#{job.title} added!"
    else
    end
    redirect_to dashboard_index_path
  end

  def edit
    @job = current_user.jobs.find(params[:id])
    @statuses = Status.all
  end

  def update
    job = current_user.jobs.find(params[:id])
    if job.update(job_params)
      flash[:notice] = "#{job.title} updated."
      redirect_to dashboard_index_path
    else
      @statuses = Status.all
      render :edit
    end
  end

  def destroy
    job = current_user.jobs.find(params[:id])
    if job.delete
      flash[:notice] = "#{job.title} deleted."
    else
      flash[:notice] = "Job not deleted.Try again"
    end
    redirect_to dashboard_index_path
  end


private

def job_params
  params.require(:job).permit(:company, :title, :city, :state, :description,
    :salary, :post_url, :status_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_user

  def create
    if user = User.from_omniauth(request.env["omniauth.auth"])
      session[:user_id] = user.id
      flash[:notice] = "Successfully logged in as #{user.first_name}"
      redirect_to dashboard_index_path
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end

end

app/helpers/checklists_helper.rb
module ChecklistsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/checklists/new.erb
<div class="container">
  <div class="row">
    <div class="col">
    </div>
    <div class="col-6">
      <div class="card new-job">
        <div class="container">
          <h3 class="card-header">Add a Job</h3>
          <div class-"card-block">
            <%= bootstrap_form_for([:job, @checklist]) do |f| %>
            <% if @checklist.errors.any? %>
            <h3><%= pluralize(@checklist.errors.count, "error") %> prohibited this record from being saved:</h3>
            <ul>
              <% @checklist.errors.full_messages.each do |message| %>
              <li>
                <%= message %>
              </li>
              <% end %>
            </ul>
            <% end %>
            <%= f.text_field :task %>

            <%= f.submit "Add Task", class: "btn-success" %>
            <% end %>
          </div>
        </div>

      </div>
    </div>
    <div class="col">
    </div>
  </div>
</div>

app/views/companies/show.erb
<div class="container">
  <div class="card">
    <div class="container">
<h1>Company Details</h1>

<p><%= @job.title %> at <%= @company.name %></p>

<div class="row">
    <div class="col-2">
      <%= image_tag @company.square_logo, width: "180em"%>
    </div>
    <div class="col-4">
      <p><%= link_to "website", "https://#{@company.website}" %></p>
      <p>Industry: <%= @company.industry %></p>
      <p>Overall, employees are <%= @company.rating_description %> with <%= @company.name %></p>
    </div>
    <div class="col-6">
      <p>Featured Pros</p>
      <p><%= @company.featured_review_pros %></p><br>
      <p>Featured Cons</p>
      <p><%= @company.featured_review_cons %></p>
    </div>
</div>

</div>
</div>
<div class="card">
  <div class="container mb-5">
<div class="row">
  <div class="col-4">
  <br><p>Overall Company Rating</p>
  <p><%= @company.overall_rating %> out of 5 with <%= @company.number_of_ratings %> total ratings</p>
<div class="progress">
  <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="<%= @company.rating_to_percentage(@company.overall_rating) %>"
  aria-valuemin="0" aria-valuemax="5" style="width:<%= @company.rating_to_percentage(@company.overall_rating) %>%">
  </div>
</div>
  </div>
  <div class="col-4">
    <br><p>Culture and Values</p>
    <p><%= @company.culture_and_values_rating %> out of 5</p>
    <div class="progress">
      <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="<%= @company.rating_to_percentage(@company.culture_and_values_rating) %>"
      aria-valuemin="0" aria-valuemax="5" style="width:<%= @company.rating_to_percentage(@company.culture_and_values_rating) %>%">
  </div>
  </div>
</div>
<div class="col-4">
  <br><p>Senior Leadership</p>
  <p><%= @company.senior_leadership_rating %> out of 5</p>
  <div class="progress">
    <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="<%= @company.rating_to_percentage(@company.senior_leadership_rating) %>"
    aria-valuemin="0" aria-valuemax="5" style="width:<%= @company.rating_to_percentage(@company.senior_leadership_rating) %>%">
</div>
</div>
</div>
</div><br>
<div class="row">
<div class="col-4">
  <p>Compensation and Benefits</p>
  <p><%= @company.compensation_and_benefits_rating %> out of 5</p>
  <div class="progress">
    <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="<%= @company.rating_to_percentage(@company.compensation_and_benefits_rating) %>"
    aria-valuemin="0" aria-valuemax="5" style="width:<%= @company.rating_to_percentage(@company.compensation_and_benefits_rating) %>%">
</div>
</div>
</div>
  <div class="col-4">
    <p>Career Opportunities</p>
    <p><%= @company.career_opportunities_rating %> out of 5</p>
    <div class="progress">
      <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="<%= @company.rating_to_percentage(@company.career_opportunities_rating) %>"
      aria-valuemin="0" aria-valuemax="5" style="width:<%= @company.rating_to_percentage(@company.career_opportunities_rating) %>%">
  </div>
  </div>
  </div>
  <div class="col-4">
    <p>Work Life Balance</p>
    <p><%= @company.work_life_balance_rating %> out of 5</p>
    <div class="progress">
      <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="<%= @company.rating_to_percentage(@company.work_life_balance_rating) %>"
      aria-valuemin="0" aria-valuemax="5" style="width:<%= @company.rating_to_percentage(@company.work_life_balance_rating) %>%">
  </div>
  </div>
  </div>
</div>
</div>
</div>

app/views/contacts/edit.erb
<div class="container">
  <div class="row">
    <div class="col">
    </div>
    <div class="col-6">
      <div class="card new-job">
        <div class="container">
          <h3 class="card-header">Edit This Contact</h3>
          <div class-"card-block">
            <%= bootstrap_form_for([:job, @contact]) do |f| %>
            <% if @contact.errors.any? %>
            <h3><%= pluralize(@contact.errors.count, "error") %> prohibited this record from being saved:</h3>
            <ul>
              <% @contact.errors.full_messages.each do |message| %>
              <li>
                <%= message %>
              </li>
              <% end %>
            </ul>
            <% end %>
            <%= f.text_field :name, value: @contact.name %>
            <%= f.text_field :phone, value: @contact.phone %>
            <%= f.text_field :email, value: @contact.email %>
            <%= f.text_field :image_url, value: @contact.image_url %>

            <%= f.submit "Update Contact", class: "btn-success" %>
            <% end %>
          </div>
        </div>

      </div>
    </div>
    <div class="col">
    </div>
  </div>
</div>

app/views/contacts/new.erb
<div class="container">
  <div class="row">
    <div class="col">
    </div>
    <div class="col-6">
      <div class="card new-job">
        <div class="container">
          <h3 class="card-header">Add a Contact</h3>
          <div class-"card-block">
            <%= bootstrap_form_for([:job, @contact]) do |f| %>
            <% if @contact.errors.any? %>
            <h3><%= pluralize(@contact.errors.count, "error") %> prohibited this record from being saved:</h3>
            <ul>
              <% @contact.errors.full_messages.each do |message| %>
              <li>
                <%= message %>
              </li>
              <% end %>
            </ul>
            <% end %>
            <%= f.text_field :name %>
            <%= f.text_field :phone %>
            <%= f.text_field :email %>
            <%= f.text_field :image_url %>

            <%= f.submit "Add Contact", class: "btn-success" %>
            <% end %>
          </div>
        </div>

      </div>
    </div>
    <div class="col">
    </div>
  </div>
</div>

app/views/dashboard/index.erb
<h1><center><%= current_user.first_name %>'s Dashboard</center></h1>
<div class="row">
<div class="col-1">
</div>
  <div class="col-10">
    <div class="card jobs-table">
      <table class="table table-bordered table-hover table-trans-white">
        <thead class="thead-inverse">
          <tr>
            <th>Company</th>
            <th>Job Title</th>
            <th>Location</th>
            <th>Salary</th>
            <th>Status</th>
            <th>Details</th>
          </tr>
        </thead>
        <% if @jobs %>
        <% @jobs.each do |job| %>
        <tbody>
          <tr>
          <td><%= link_to job.company, company_path(job) %></td>
          <td><%= job.title %></td>
          <td><%= job.location %></td>
          <td><%= number_to_currency(job.salary) %></td>
          <td><%= job.status.name %></td>
          <td><%= link_to "Details", job_path(job) %></td>
        </tr>
        </tbody>
        <% end %>
        <% end %>
        <%= will_paginate @jobs %>
      </table>
    </div>
    <%= button_to '/jobs/new', method: 'get', class: "fa fa-plus-square btn-primary" do %>
    <span class="fa-fa-plus-square"></span> Add a Job
    <% end %>
  </div>
</div>
<div class="col">
</div>
</div>

app/views/jobs/edit.erb
<div class="container">
  <div class="row">
    <div class="col">
    </div>
    <div class="col-6">
      <div class="card new-job">
        <div class="container">
          <h3 class="card-header">Edit This Job</h3>
          <div class-"card-block">
            <%= bootstrap_form_for(@job) do |f| %>
            <% if @job.errors.any? %>
            <h3><%= pluralize(@job.errors.count, "error") %> prohibited this record from being saved:</h3>
            <ul>
              <% @job.errors.full_messages.each do |message| %>
              <li>
                <%= message %>
              </li>
              <% end %>
            </ul>
            <% end %>
            <%= f.text_field :company, value: @job.company %>
            <%= f.text_field :title, value: @job.title %>
            <%= f.text_area :description, value: @job.description %>
            <%= f.text_field :city, value: @job.city %>
            <%= f.text_field :state, value: @job.state %>
            <%= f.text_field :salary, value: @job.salary %>
            <%= f.text_field :post_url, value: @job.post_url %>
            <%= f.collection_select :status_id, @statuses, :id, :name %>

            <%= f.submit "Update Job", class: "btn-success" %>
            <% end %>
          </div>
        </div>

      </div>
    </div>
    <div class="col">
    </div>
  </div>
</div>

app/views/jobs/new.erb
<div class="container">
  <div class="row">
    <div class="col">
    </div>
    <div class="col-6">
      <div class="card new-job">
        <div class="container">
          <h3 class="card-header">Add a Job</h3>
          <div class-"card-block">
            <%= bootstrap_form_for(@job) do |f| %>
            <% if @job.errors.any? %>
            <h3><%= pluralize(@job.errors.count, "error") %> prohibited this record from being saved:</h3>
            <ul>
              <% @job.errors.full_messages.each do |message| %>
              <li>
                <%= message %>
              </li>
              <% end %>
            </ul>
            <% end %>
            <%= f.text_field :company %>
            <%= f.text_field :title %>
            <%= f.text_area :description %>
            <%= f.text_field :city %>
            <%= f.text_field :state %>
            <%= f.text_field :salary %>
            <%= f.text_field :post_url %>
            <%= f.collection_select :status_id, @statuses, :id, :name %>

            <%= f.submit "Add Job", class: "btn-success" %>
            <% end %>
          </div>
        </div>

      </div>
    </div>
    <div class="col">
    </div>
  </div>
</div>

app/views/jobs/show.erb
<div class="container">
  <div class="card">
  <h1>Job Details</h1>

  <p><%= @job.title %> at <%= @company.name %></p>

  <div class="row">
    <div class="col-2">
      <%= image_tag @company.square_logo, width: "180em" %>
    </div>
    <div class="col-4">
      <p><%= link_to "#{@company.name}'s website", "https://#{@company.website}" %></p>
      <p>Industry: <%= @company.industry %></p>
      <p>Status: <%= @job.status.name %></p>
      <p><%= link_to "Edit Job", edit_job_path(@job) %></p>
      <p><%= link_to "Delete Job", job_path(@job), method: 'delete' %></p>
      <p>Contacts:</p>
      <% @job.contacts.each do |contact| %>
      <ul>
        <li><%= link_to contact.name, edit_job_contact_path(@job, contact) %></li>
        <li><%= contact.phone %></li>
        <li><%= contact.email %></li>
        <%= link_to "delete contact", job_contact_path(@job, contact), method: 'delete' %>
      </ul>
      <% end %>
      <%= link_to "Add Contact", new_job_contact_path(@job) %>
    </div>

    <div class="col-6">
      <p>Description:</p>
      <p><%= @job.description %></p><br>
    </div>
  </div>
</div>
<div class="card">
  <div class="container mb-5">
    <div class="row">
      <div class="col-12">
        <center><p>Analysis of this post has produced these keywords. They can help to write a stronger cover letter:</p></center>
      </div>
      <% @keywords.each do |keyword| %>
      <div class="col-4">
        <p><%= keyword.word %>, relevance <%= keyword.relevance %></p>
      </div>
      <% end %>
    </div><br>
  </div>
</div>
<div class="card">
  <div class="container mb-5">
    <div class="row">
      <div class="col-12">
        <center><p>Checklist tasks for this job:</p></center>
      </div>
      <% @job.checklists.each do |checklist| %>
      <div class="col-4">
        <p><%= checklist.task %>  <%= link_to "Delete, I'm done!", job_checklist_path(@job, checklist), method: 'delete' %></p>
      </div>
      <% end %>
      <%= link_to "Add Task", new_job_checklist_path(@job) %>
    </div><br>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JobHunt</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <nav class="navbar sticky-top nav-style">
    <%= image_tag 'logo.png', class: "logo-img" %>
    <% if current_user %>
    <ul class="navbar-right list-inline">
      <li class="list-inline-item"><%= link_to "Dashboard", dashboard_index_path, class: 'text-muted' %></li>
      <li class="list-inline-item"><%= link_to "Logout", logout_path, class: 'text-muted', method: :delete %></li>
    </ul>
    <% end %>
  </nav>
  <% flash.each do |name, msg| %>
  <div class="transparent-white"><%= content_tag :div, sanitize(msg), class: name %></div>
  <% end %>
  <%= yield %>
</body>
</html>